site_name: MkDocsPage
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  language: zh
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
use_directory_urls: false
docs_dir: D:\001Code\markdown gui\test\docs
site_dir: D:\001Code\markdown gui\test\site
markdown_extensions:
- markdown_captions
- sane_lists
- admonition
- pymdownx.details
- nl2br
- def_list
- footnotes
- meta
- md_in_html
- toc:
    marker: '[toc]'
    permalink: true
- tables
- admonition: {}
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
